### ISSUE TITLE
`DatepickerRange` component gives "Cannot update a component (xxx) while rendering a different component (`DatepickerRange`)" warning

### ISSUE THREAD

**Issue by DariaRadu** [zendeskgarden/react-components#1174] opened 2021-09-08 13:21 UTC
## Expectations

When following the example in the [DatepickerRange](https://garden.zendesk.com/components/date-picker#date-range) documentation, the code should work without errors/warnings.

## Reality

When setting the `startValue`/ `endValue` state using the same code as the example, the following warning pops up.
![image](https://user-images.githubusercontent.com/21333467/132517458-35aaf2d7-b302-4533-ac0b-0361ddb507c2.png)
![image](https://user-images.githubusercontent.com/21333467/132517487-7b3da4be-c71e-43ae-9551-aff2be38805b.png)

## Steps to Reproduce

1. Use the code in the documented example inside of another component.
2. Change the start value/end value
3. (Optional) The current implementation has the datepicker in a dropdown. We are not sure if that might affect it.

### Fine Print

- Component: `DatepickerRange`
- Version: `8.39.0`
- Browsers: Chrome

**Comment by jzempel** [comment] 2021-09-09 14:46
Thanks @DariaRadu. This is a duplicate of #1092. Garden has this in the backlog and will schedule a fix as soon as possible.

**Closed by jzempel** 2021-09-09 14:46 UTC
