### ISSUE TITLE
Support rendering TooltipModal in a Portal

### ISSUE THREAD

**Issue by yara-simargil** [zendeskgarden/react-components#1520] opened 2023-02-21 13:12 UTC
## Expectations

Focus works when the component is used inside a Portal.

## Reality

Focus is broken when the component is wrapped in a Portal.

## Steps to Reproduce

1. Wrap TooltipModal component in a Portal: `ReactDOM.createPortal(<TooltipModal />, document.body)`
2. Add several tabable components inside the tooltip.
3. Try to tab through the tooltip - buttons keep focused styles.

<img width="466" alt="Screenshot 2023-02-21 at 14 10 06" src="https://user-images.githubusercontent.com/1819404/220353665-60a43bda-0514-4af8-a4ff-8d1bc27419f9.png">

Check out this sandbox: https://codesandbox.io/s/focused-wright-4nhtfm?file=/src/Example.tsx

### Fine Print

- Component: TooltipModal
- Version: 8.63.1
- Browsers: all

**Comment by Francois-Esquire** [comment] 2023-04-28 20:16
Hey @yara-simargil thank you for reporting this! After some investigation, I noticed that focus (the `document.activeElement`) is correct however the focus styling has been scrambled and off-beat. I'll have this tracked so we can tackle it in the near future!

**Comment by nermin-io** [comment] 2023-12-05 04:20
Any updates on the issue? It seems it also affects other components such as `<Input />` when wrapped in a portal.

**Comment by geotrev** [comment] 2024-01-22 19:31
Hi @nermin-io @yara-simargil - follow up after debugging this issue.

The issue is `document.body` is outside your ThemeProvider boundary. Essentially, the focus state never dismisses because the theme can't be found and the inner styled component silently errors, retaining its previous state.

I've demonstrated this behavior by [updating the original example](https://codesandbox.io/p/sandbox/objective-field-48gvhc).

If you have any additional questions, let us know!

**Comment by geotrev** [comment] 2024-02-03 18:14
Closing the issue for now, given the above solution. Feel free to make a new issue if you run into something else!

**Closed by geotrev** 2024-02-03 18:14 UTC
