### ISSUE TITLE
Maximum update depth exceeded with textarea component

### ISSUE THREAD

**Issue by tommoor** [zendeskgarden/react-components#1563] opened 2023-06-28 16:40 UTC
## Expectations

Textarea expands with content

## Reality

Maximum update depth exceeded – plugin "crashes" – see video:

https://github.com/zendeskgarden/react-components/assets/380914/812c15e0-a8aa-4b84-9d3a-d1b625125f5a

We were able to pinpoint the setState loop to this code:

![image](https://github.com/zendeskgarden/react-components/assets/380914/79bf87e5-d618-487e-ae4e-56b1f600eb26)

## Steps to Reproduce

For reproduction steps, we have a Zendesk textarea component like this inside a plugin:

```
<Textarea minRows={4} maxRows={10} isCompact {...field} />
```

Typing enough enters so that the textarea expands causes a setState loop inside of the Textarea component. This is causing our shared customers to lose their data on a regular basis.

### Fine Print

- Component: Textarea
- Version: 8.62.1
- Browsers: Chrome+Brave, maybe all

**Comment by geotrev** [comment] 2023-06-28 20:54
Hi @tommoor - can you build an [isolated reproduction](https://codesandbox.io/s/vigorous-noether-5xhy98?file=/src/Example.tsx)? I'm not able to reproduce in dev or from our production [Storybook demo](https://zendeskgarden.github.io/react-components/?path=/story/packages-forms-textarea--uncontrolled&args=isCompact:true;minRows:4;maxRows:10).

Thanks!

**Comment by tommoor** [comment] 2023-06-28 21:20
I also am unable to repro in Storybook, it seems related to running inside the Zendesk plugin environment

**Comment by jzempel** [comment] 2023-06-29 14:36
@tommoor what version of React are you using?

**Comment by tommoor** [comment] 2023-06-29 15:27
We are using `18.2.0` and StrictMode.

**Comment by jzempel** [comment] 2023-07-18 21:20
Closing for now. Please re-open if there's an isolated reproduction.

**Comment by tommoor** [comment] 2023-07-18 22:27
Is there someone on your plugins/extensions team that can look at this?

**Comment by tommoor** [comment] 2023-07-20 16:16
Thoughts? This is a disappointing response – we have hundreds of shared customers experiencing data loss due to this crash.

Would it be possible for someone on Zendesk's side to try our production plugin and reproduce the issue? It doesn't reproduce in development which is part of the problem.

**Comment by jzempel** [comment] 2023-07-20 20:13
Our team is continuing to look into possible causes. But without an environment to reproduce, we're stuck making guesses. If your team happens upon a solution, we're happy to work with you to accept [contributions](https://github.com/zendeskgarden/react-components/blob/main/.github/CONTRIBUTING.md).

**Comment by tommoor** [comment] 2023-07-20 20:16
This is the one: https://www.zendesk.com/marketplace/apps/support/431018/linear/

**Comment by Francois-Esquire** [comment] 2023-07-21 16:01
Hi @tommoor have you tried using an [error boundary component](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) to recover from data loss? It can also help us isolate the problem and find out what's happening with the `Textarea` or other factors at play.

**Comment by jzempel** [comment] 2024-01-19 15:27
Thanks to @tgohn for a minimal reproduction sandbox: https://codesandbox.io/p/sandbox/zen-kalam-7kkw8j?file=%2Fsrc%2Findex.tsx%3A13%2C40

**Closed** 2024-01-19 20:53 UTC
