### ISSUE TITLE
Keyboard interaction for `Dropdown`s

### ISSUE THREAD

**Issue by fredefox** [zendeskgarden/react-components#452] opened 2019-09-13 12:41 UTC
In the example list here: https://garden.zendesk.com/react-components/dropdowns/#!/Menu%20usage/1

If you remove the `onSelect` property of the `Dropdown` and an analogous `onClick` to the child `Item` elements then I would expect the behavior to be the same but it's not. It works if you use the mouse, but if you:

1. tab onto the button
2. hit enter
3. arrow down
4. enter

Then I'd expect the alert box to pop up, yet it doesn't.

For reference here is the full modified example:

```
const { Button } = require('@zendeskgarden/react-buttons/src');
const { IconButton, Icon } = require('@zendeskgarden/react-buttons/src');
const SettingsIcon = require('@zendeskgarden/svg-icons/src/16/gear-stroke.svg').default;

<Grid>
  <Row>
    <Col md>
      <Dropdown>
        <Trigger>
          <Button>Default Menu</Button>
        </Trigger>
        <Menu>
          <Item onClick={item => alert(item)} value="option-1">Option 1</Item>
        </Menu>
      </Dropdown>
    </Col>
  </Row>
</Grid>;
```

**Comment by austin94** [comment] 2019-09-13 14:49
I believe this is intended behavior. We allow _any_ props to be spread onto an element, which includes the `onClick`.

For our Menus, Select, Autocompletes, and Multiselects we use the `aria-activedescendant` model for screenreader support. This requires that the wrapping element (Menu) receives focus throughout the interaction.

Also, only `<buttons>` (I think) are able to have their `onClick` triggered by `enter/space`. Our menu items are `<li>` elements.

Users are required to use the `onSelect` prop to receive selection whether it's click, keyboard, or otherwise.

**Comment by fredefox** [comment] 2019-09-16 09:01
I think the fact that `Item`s are essentially embellished `li`-elements sufficiently explains why keyboard interactions does not trigger their `onclick` handler. However, I would argue that we're already breaking the semantic properties of`li` in that `Item`s can be selected. Both by hovering with the mouse and with keyboard navigation.

**Comment by austin94** [comment] 2019-09-16 16:21
> However, I would argue that we're already breaking the semantic properties of li

You are correct, which is why `[role="option"]` is applied for screen-readers. This is all handled by [downshift](https://github.com/downshift-js/downshift) which goes into more detail about the attributes and events it supports.

I'm going to close this for now. If you have any additional questions feel free to re-open.

**Closed by austin94** 2019-09-16 16:21 UTC
